# Generated by Django 4.1.2 on 2022-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='questions',
            table='employee',
        ),
    ]
