# Generated by Django 4.1.2 on 2022-10-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questions_text_alter_questions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
